(* Copyright 2026 Bloomberg Finance L.P. *)
(* Distributed under the terms of the Apache 2.0 license. *)

(** The Shannon switching game: Lehman's theorem, positive direction. *)

From Stdlib Require Import List.
From Stdlib Require Import PeanoNat.
From Stdlib Require Import Psatz.
From Stdlib Require Import Bool.

Import ListNotations.

Require Import GameTrees.Helpers.
Require Import GameTrees.Determinacy.
Require Import GameTrees.Y.
Require Import GameTrees.Reach.

(** * Edges *)

(** Undirected edges as ordered pairs, queried up to orientation. *)
Definition edge : Type := (cell * cell)%type.

Definition edge_eq_dec : forall e1 e2 : edge, {e1 = e2} + {e1 <> e2}.
Proof. decide equality; apply cell_eq_dec. Defined.

Definition edge_eqb (e1 e2 : edge) : bool :=
  if edge_eq_dec e1 e2 then true else false.

Lemma edge_eqb_true_iff : forall e1 e2, edge_eqb e1 e2 = true <-> e1 = e2.
Proof.
  intros e1 e2; unfold edge_eqb; destruct (edge_eq_dec e1 e2);
    split; congruence.
Qed.

Definition ememb (e : edge) (E : list edge) : bool := existsb (edge_eqb e) E.

Lemma ememb_true_iff : forall e E, ememb e E = true <-> In e E.
Proof.
  intros e E; unfold ememb; rewrite existsb_exists; split.
  - intros [x [Hx He]]; apply edge_eqb_true_iff in He; subst; auto.
  - intros Hin; exists e; split; auto; apply edge_eqb_true_iff; auto.
Qed.

Lemma ememb_false_iff : forall e E, ememb e E = false <-> ~ In e E.
Proof.
  intros e E; split.
  - intros Hm Hin; apply ememb_true_iff in Hin; congruence.
  - intros Hn; destruct (ememb e E) eqn:Em; auto.
    apply ememb_true_iff in Em; contradiction.
Qed.

Definition remove_edge (e : edge) (E : list edge) : list edge :=
  filter (fun x => negb (edge_eqb x e)) E.

Lemma in_remove_edge :
  forall e E x, In x (remove_edge e E) <-> In x E /\ x <> e.
Proof.
  intros e E x; unfold remove_edge; rewrite filter_In.
  rewrite negb_true_iff; split.
  - intros [Hin Hne]; split; auto.
    intros ->.
    rewrite (proj2 (edge_eqb_true_iff e e) eq_refl) in Hne; discriminate.
  - intros [Hin Hne]; split; auto.
    destruct (edge_eqb x e) eqn:Ee; auto.
    apply edge_eqb_true_iff in Ee; congruence.
Qed.

Lemma remove_edge_length_le :
  forall e E, length (remove_edge e E) <= length E.
Proof.
  intros e E; induction E as [|x E IH]; simpl; [lia|].
  destruct (negb (edge_eqb x e)); simpl; lia.
Qed.

Lemma remove_edge_length_lt :
  forall e E, In e E -> length (remove_edge e E) < length E.
Proof.
  intros e E Hin; induction E as [|x E IH]; [destruct Hin|].
  destruct Hin as [-> | Hin].
  - assert (He : edge_eqb e e = true)
      by (apply edge_eqb_true_iff; auto).
    unfold remove_edge; simpl; rewrite He; simpl.
    pose proof (remove_edge_length_le e E) as Hle.
    unfold remove_edge in Hle; lia.
  - specialize (IH Hin).
    unfold remove_edge in *; simpl.
    destruct (negb (edge_eqb x e)); simpl; lia.
Qed.

(** Vertex adjacency generated by an edge list, up to orientation. *)
Definition adjE (E : list edge) (p q : cell) : Prop :=
  In (p, q) E \/ In (q, p) E.

Definition adjEb (E : list edge) (p q : cell) : bool :=
  existsb (fun e => (cell_eqb (fst e) p && cell_eqb (snd e) q)
                 || (cell_eqb (fst e) q && cell_eqb (snd e) p)) E.

Lemma adjEb_true_iff : forall E p q, adjEb E p q = true <-> adjE E p q.
Proof.
  intros E p q; unfold adjEb, adjE; rewrite existsb_exists; split.
  - intros [[a b] [Hin He]]; simpl in He.
    apply orb_true_iff in He; destruct He as [He | He];
      apply andb_true_iff in He; destruct He as [H1 H2];
      apply cell_eqb_true_iff in H1; apply cell_eqb_true_iff in H2;
      subst; auto.
  - intros [Hin | Hin].
    + exists (p, q); split; auto; simpl.
      apply orb_true_iff; left; apply andb_true_iff;
        split; apply cell_eqb_true_iff; auto.
    + exists (q, p); split; auto; simpl.
      apply orb_true_iff; right; apply andb_true_iff;
        split; apply cell_eqb_true_iff; auto.
Qed.

Lemma adjE_sym : forall E p q, adjE E p q -> adjE E q p.
Proof. unfold adjE; tauto. Qed.

Lemma adjE_incl :
  forall E E' p q, incl E E' -> adjE E p q -> adjE E' p q.
Proof.
  intros E E' p q Hincl [H | H]; [left | right]; apply Hincl; auto.
Qed.

(** * Chain symmetry and edge surgery *)

Lemma chain_sym :
  forall (G : cell -> Prop) (A : cell -> cell -> Prop),
    (forall x y, A x y -> A y x) ->
    forall p q, chain G A p q -> chain G A q p.
Proof.
  intros G A Hsym p q ch; induction ch as [p HG | p q r HG HA ch IH].
  - apply chain_refl; auto.
  - eapply chain_snoc; eauto.
Qed.

(** A chain either avoids a given edge or decomposes through its endpoints. *)
Lemma chain_avoid :
  forall (G : cell -> Prop) (E : list edge) (u1 u2 : cell),
    G u1 -> G u2 ->
    forall p x, chain G (adjE E) p x ->
    chain G (adjE (remove_edge (u1, u2) E)) p x \/
    (chain G (adjE (remove_edge (u1, u2) E)) p u1 /\
     chain G (adjE (remove_edge (u1, u2) E)) u2 x) \/
    (chain G (adjE (remove_edge (u1, u2) E)) p u2 /\
     chain G (adjE (remove_edge (u1, u2) E)) u1 x).
Proof.
  intros G E u1 u2 Hg1 Hg2 p x ch.
  set (E' := remove_edge (u1, u2) E) in *.
  assert (Hsym : forall a b, adjE E' a b -> adjE E' b a)
    by (intros; apply adjE_sym; auto).
  induction ch as [p HG | p q x HG HA ch IH].
  - left; apply chain_refl; auto.
  - destruct (adjEb E' p q) eqn:Estep.
    + apply adjEb_true_iff in Estep.
      destruct IH as [H | [[H1 H2] | [H1 H2]]].
      * left; eapply chain_step; eauto.
      * right; left; split; auto; eapply chain_step; eauto.
      * right; right; split; auto; eapply chain_step; eauto.
    + assert (Hdel : (p = u1 /\ q = u2) \/ (p = u2 /\ q = u1)).
      { destruct HA as [HA | HA].
        - destruct (edge_eq_dec (p, q) (u1, u2)) as [He | Hne].
          + inversion He; auto.
          + exfalso.
            assert (Hs : adjE E' p q)
              by (left; apply in_remove_edge; split; auto).
            apply adjEb_true_iff in Hs; congruence.
        - destruct (edge_eq_dec (q, p) (u1, u2)) as [He | Hne].
          + inversion He; auto.
          + exfalso.
            assert (Hs : adjE E' p q)
              by (right; apply in_remove_edge; split; auto).
            apply adjEb_true_iff in Hs; congruence. }
      destruct Hdel as [[-> ->] | [-> ->]].
      * destruct IH as [H | [[H1 H2] | [H1 H2]]].
        -- right; left; split; auto; apply chain_refl; auto.
        -- left; eapply chain_trans; [|exact H2].
           apply chain_sym; auto.
        -- left; exact H2.
      * destruct IH as [H | [[H1 H2] | [H1 H2]]].
        -- right; right; split; auto; apply chain_refl; auto.
        -- left; exact H2.
        -- left; eapply chain_trans; [|exact H2].
           apply chain_sym; auto.
Qed.

(** * Spanning subgraphs *)

Definition ends_in (W : list cell) (H : list edge) : Prop :=
  forall e, In e H -> In (fst e) W /\ In (snd e) W.

(** [spans W H]: the edges of [H] live on [W] and connect all of [W]. *)
Definition spans (W : list cell) (H : list edge) : Prop :=
  ends_in W H /\
  forall u v, In u W -> In v W ->
    chain (fun p => In p W) (adjE H) u v.

(** Every vertex of [W] reaches an endpoint of a deleted spanning edge. *)
Lemma endpoint_reach :
  forall W H u1 u2 x,
    spans W H -> In (u1, u2) H -> In x W ->
    chain (fun p => In p W) (adjE (remove_edge (u1, u2) H)) u1 x \/
    chain (fun p => In p W) (adjE (remove_edge (u1, u2) H)) u2 x.
Proof.
  intros W H u1 u2 x [Hends Hconn] He Hx.
  destruct (Hends _ He) as [Hu1 Hu2]; simpl in Hu1, Hu2.
  destruct (chain_avoid (fun p => In p W) H u1 u2 Hu1 Hu2 u1 x
              (Hconn u1 x Hu1 Hx))
    as [Hc | [[Ha Hb] | [Ha Hb]]].
  - left; exact Hc.
  - right; exact Hb.
  - left; exact Hb.
Qed.

(** A punctured spanning subgraph spans again once its ends are rejoined. *)
Lemma spans_of_bridge :
  forall W HA u1 u2 (H' : list edge),
    spans W HA -> In (u1, u2) HA ->
    incl (remove_edge (u1, u2) HA) H' ->
    ends_in W H' ->
    chain (fun p => In p W) (adjE H') u1 u2 ->
    spans W H'.
Proof.
  intros W HA u1 u2 H' HspA He Hincl Hends Hbr.
  assert (Hsym : forall a b, adjE H' a b -> adjE H' b a)
    by (intros; apply adjE_sym; auto).
  assert (Hlift : forall x y,
      chain (fun p => In p W) (adjE (remove_edge (u1, u2) HA)) x y ->
      chain (fun p => In p W) (adjE H') x y).
  { intros x y Hch.
    eapply chain_impl; [| |exact Hch]; auto.
    intros a b Hab; eapply adjE_incl; eauto. }
  assert (Hbr' : chain (fun p => In p W) (adjE H') u2 u1)
    by (apply chain_sym; auto).
  split; auto.
  intros u v Hu Hv.
  assert (Hcu : chain (fun p => In p W) (adjE H') u1 u \/
                chain (fun p => In p W) (adjE H') u2 u).
  { destruct (endpoint_reach W HA u1 u2 u HspA He Hu); [left | right];
      apply Hlift; auto. }
  assert (Hcv : chain (fun p => In p W) (adjE H') u1 v \/
                chain (fun p => In p W) (adjE H') u2 v).
  { destruct (endpoint_reach W HA u1 u2 v HspA He Hv); [left | right];
      apply Hlift; auto. }
  destruct Hcu as [Hcu | Hcu]; destruct Hcv as [Hcv | Hcv].
  - eapply chain_trans; [apply (chain_sym _ _ Hsym); exact Hcu | exact Hcv].
  - eapply chain_trans; [apply (chain_sym _ _ Hsym); exact Hcu |].
    eapply chain_trans; [exact Hbr | exact Hcv].
  - eapply chain_trans; [apply (chain_sym _ _ Hsym); exact Hcu |].
    eapply chain_trans; [exact Hbr' | exact Hcv].
  - eapply chain_trans; [apply (chain_sym _ _ Hsym); exact Hcu | exact Hcv].
Qed.

(** * The switching game *)

Section Shannon.
  Variable V : list cell.
  Hypothesis HV : NoDup V.
  Variables strm trm : cell.
  Hypothesis Hst : In strm V.

    (** States: available edges, claimed edges, and the turn. *)
  Record sg : Type := MkSG { avail : list edge; claimed : list edge;
                             cturn : bool }.

    (** Both players choose an available edge: Cut deletes, Short claims. *)
  Definition sg_moves (st : sg) : list edge := avail st.

  Definition sg_play (st : sg) (e : edge) : sg :=
    if cturn st
    then MkSG (remove_edge e (avail st)) (claimed st) false
    else MkSG (remove_edge e (avail st)) (e :: claimed st) true.

  Definition sg_amove (st : sg) : bool := cturn st.

  Definition connb (E : list edge) : bool :=
    memb trm (reach_from V (fun p => memb p V) (adjEb E) [strm]).

  (** The terminals are joined by a chain of [E]-edges inside [V]. *)
  Definition connectedE (E : list edge) : Prop :=
    chain (fun p => In p V) (adjE E) strm trm.

  Lemma connb_true_iff : forall E, connb E = true <-> connectedE E.
  Proof.
    intros E; unfold connb, connectedE; split.
    - intros Hm; apply memb_true_iff in Hm.
      destruct (reach_from_sound V (fun p => memb p V) (adjEb E) [strm])
        with (p := trm) as [a [Ha Hch]]; auto.
      { intros a [<- | []]; unfold Gb; apply memb_true_iff; auto. }
      destruct Ha as [<- | []].
      eapply chain_impl; [| | exact Hch].
      + intros z Hz; apply memb_true_iff; exact Hz.
      + intros z y Hzy; apply adjEb_true_iff; exact Hzy.
    - intros Hch; apply memb_true_iff.
      eapply reach_from_complete with (a := strm); eauto.
      + constructor; [intros [] | constructor].
      + intros z [<- | []]; auto.
      + intros z Hz; apply memb_true_iff; auto.
      + left; auto.
      + eapply chain_impl; [| | exact Hch].
        * intros z Hz; unfold Gb; apply memb_true_iff; exact Hz.
        * intros z y Hzy; unfold Ab; apply adjEb_true_iff; exact Hzy.
  Qed.

    (** Short wins on connecting the terminals, Cut when no edges can. *)
  Definition sg_outc (st : sg) : option outcome :=
    if connb (claimed st) then Some (win false)
    else if connb (avail st ++ claimed st) then None
    else Some (win true).

  (** The Shannon game is decided, never drawn. *)
  Lemma sg_outc_not_drawn : forall st, sg_outc st <> Some drawn.
  Proof.
    intros st H; unfold sg_outc in H.
    destruct (connb (claimed st)); [discriminate|].
    destruct (connb (avail st ++ claimed st)); discriminate.
  Qed.

  Lemma sg_outc_none_elim :
    forall st, sg_outc st = None ->
    connb (claimed st) = false /\ connb (avail st ++ claimed st) = true.
  Proof.
    intros st H; unfold sg_outc in H.
    destruct (connb (claimed st)); [discriminate|].
    destruct (connb (avail st ++ claimed st)); [auto | discriminate].
  Qed.

  (** An undecided position always has an available edge. *)
  Lemma avail_nonempty_of_none :
    forall st, sg_outc st = None -> avail st <> [].
  Proof.
    intros st H Hnil.
    apply sg_outc_none_elim in H; destruct H as [Hc Hu].
    rewrite Hnil in Hu; simpl in Hu; congruence.
  Qed.

  (** ** The Short invariant *)

  (** Claimed and available edges never overlap. *)
  Definition sg_wf (st : sg) : Prop :=
    forall e, In e (claimed st) -> ~ In e (avail st).

    (** The certificate: two spanning subgraphs overlapping only in claims. *)
  Definition sg_good (st : sg) (W : list cell) (H1 H2 : list edge) : Prop :=
    NoDup W /\ incl W V /\ In strm W /\ In trm W /\
    incl H1 (avail st ++ claimed st) /\
    incl H2 (avail st ++ claimed st) /\
    (forall e, In e H1 -> In e H2 -> In e (claimed st)) /\
    spans W H1 /\ spans W H2.

  Definition sg_inv (st : sg) : Prop := exists W H1 H2, sg_good st W H1 H2.

  Lemma sg_good_intro :
    forall st W H1 H2,
      NoDup W -> incl W V -> In strm W -> In trm W ->
      incl H1 (avail st ++ claimed st) ->
      incl H2 (avail st ++ claimed st) ->
      (forall e, In e H1 -> In e H2 -> In e (claimed st)) ->
      spans W H1 -> spans W H2 ->
      sg_good st W H1 H2.
  Proof.
    intros st W H1 H2 HW HWV HsW HtW HH1 HH2 Hsh Hsp1 Hsp2.
    exact (conj HW (conj HWV (conj HsW (conj HtW (conj HH1 (conj HH2
             (conj Hsh (conj Hsp1 Hsp2)))))))).
  Qed.

  Lemma sg_good_swap :
    forall st W H1 H2, sg_good st W H1 H2 -> sg_good st W H2 H1.
  Proof.
    intros st W H1 H2
      (HW & HWV & HsW & HtW & HH1 & HH2 & Hshare & Hsp1 & Hsp2).
    apply sg_good_intro; auto.
  Qed.

  Lemma spans_connectedE :
    forall W H, incl W V -> In strm W -> In trm W ->
      spans W H -> forall E, incl H E -> connectedE E.
  Proof.
    intros W H HWV HsW HtW [Hends Hconn] E HHE.
    unfold connectedE.
    eapply chain_impl; [| | apply Hconn; auto].
    - intros z Hz; apply HWV; auto.
    - intros z y Hzy; eapply adjE_incl; eauto.
  Qed.

  (** ** Wellformedness and accounting across moves *)

  Lemma sg_wf_play : forall st e, sg_wf st -> sg_wf (sg_play st e).
  Proof.
    intros st e Hwf x; unfold sg_play.
    destruct (cturn st); simpl.
    - intros Hc Ha; apply in_remove_edge in Ha.
      exact (Hwf x Hc (proj1 Ha)).
    - intros [<- | Hc] Ha; apply in_remove_edge in Ha.
      + exact ((proj2 Ha) eq_refl).
      + exact (Hwf x Hc (proj1 Ha)).
  Qed.

  Lemma cturn_play_cut :
    forall st e, cturn st = true -> cturn (sg_play st e) = false.
  Proof. intros st e Hc; unfold sg_play; rewrite Hc; auto. Qed.

  Lemma cturn_play_short :
    forall st e, cturn st = false -> cturn (sg_play st e) = true.
  Proof. intros st e Hc; unfold sg_play; rewrite Hc; auto. Qed.

  Lemma in_union_cut :
    forall st e x,
      sg_wf st -> In e (avail st) -> cturn st = true ->
      (In x (avail (sg_play st e) ++ claimed (sg_play st e)) <->
       In x (avail st ++ claimed st) /\ x <> e).
  Proof.
    intros st e x Hwf He Hc; unfold sg_play; rewrite Hc; simpl.
    rewrite !in_app_iff, in_remove_edge; split.
    - intros [[Hx Hne] | Hx]; [tauto|].
      split; [auto|].
      intros ->; exact (Hwf e Hx He).
    - intros [[Hx | Hx] Hne]; tauto.
  Qed.

  Lemma in_union_short :
    forall st e x,
      In e (avail st) -> cturn st = false ->
      (In x (avail (sg_play st e) ++ claimed (sg_play st e)) <->
       In x (avail st ++ claimed st)).
  Proof.
    intros st e x He Hc; unfold sg_play; rewrite Hc; simpl.
    rewrite !in_app_iff, in_remove_edge; simpl; split.
    - intros [[Hx _] | [Heq | Hx]]; [tauto | | tauto].
      subst x; tauto.
    - intros [Hx | Hx]; [| tauto].
      destruct (edge_eq_dec x e) as [-> | Hne].
      + right; left; reflexivity.
      + left; split; auto.
  Qed.

  (** One-directional forms of the accounting lemmas, for forward use. *)
  Lemma union_cut_of :
    forall st e x,
      sg_wf st -> In e (avail st) -> cturn st = true ->
      In x (avail st ++ claimed st) -> x <> e ->
      In x (avail (sg_play st e) ++ claimed (sg_play st e)).
  Proof.
    intros st e x Hwf He Hc Hx Hne.
    apply (in_union_cut st e x); auto.
  Qed.

  Lemma union_short_of :
    forall st e x,
      In e (avail st) -> cturn st = false ->
      In x (avail st ++ claimed st) ->
      In x (avail (sg_play st e) ++ claimed (sg_play st e)).
  Proof.
    intros st e x He Hc Hx.
    apply (in_union_short st e x); auto.
  Qed.

  (** A Short claim preserves the certificate outright. *)
  Lemma sg_good_short_claim :
    forall st c W H1 H2,
      In c (avail st) -> cturn st = false ->
      sg_good st W H1 H2 -> sg_good (sg_play st c) W H1 H2.
  Proof.
    intros st c W H1 H2 Hc Hturn
      (HW & HWV & HsW & HtW & HH1 & HH2 & Hshare & Hsp1 & Hsp2).
    apply sg_good_intro; auto.
    - intros x Hx; apply union_short_of; auto.
    - intros x Hx; apply union_short_of; auto.
    - intros e He1 He2; unfold sg_play; rewrite Hturn; simpl.
      right; exact (Hshare e He1 He2).
  Qed.

    (** Some claim preserves the certificate from a Short-to-move position. *)
  Lemma claim_any :
    forall st W H1 H2,
      sg_outc st = None -> cturn st = false ->
      sg_good st W H1 H2 ->
      exists c, In c (avail st) /\ sg_inv (sg_play st c).
  Proof.
    intros st W H1 H2 Hnone Hturn Hg.
    destruct (avail st) as [|c rest] eqn:Ea.
    - exfalso; eapply avail_nonempty_of_none; eauto.
    - exists c; split; [left; auto|].
      exists W, H1, H2.
      apply sg_good_short_claim; auto.
      rewrite Ea; left; auto.
  Qed.

  (** ** The repair lemma *)

  Lemma reach_seed_in :
    forall W (goodb : cell -> bool) adjb u,
      In u (reach_from W goodb adjb [u]).
  Proof.
    intros W goodb adjb u.
    unfold reach_from.
    apply (iterate_incl W goodb adjb (length W) [u]).
    left; auto.
  Qed.

    (** A punctured subgraph stays connected or a crossing edge repairs it. *)
  Lemma split_repair :
    forall W HA HB u1 u2,
      NoDup W ->
      spans W HA -> spans W HB ->
      In (u1, u2) HA -> ~ In (u1, u2) HB ->
      spans W (remove_edge (u1, u2) HA) \/
      exists f, In f HB /\ ~ In f HA /\ f <> (u1, u2) /\
        spans W (f :: remove_edge (u1, u2) HA).
  Proof.
    intros W HA HB u1 u2 HW HspA HspB He HeB.
    pose proof HspA as [HendsA HconnA].
    pose proof HspB as [HendsB HconnB].
    destruct (HendsA _ He) as [Hu1 Hu2]; simpl in Hu1, Hu2.
    set (HA' := remove_edge (u1, u2) HA).
    set (K := reach_from W (fun p => memb p W) (adjEb HA') [u1]).
    assert (HKsound : forall x, In x K ->
      chain (fun p => In p W) (adjE HA') u1 x).
    { intros x Hx.
      destruct (reach_from_sound W (fun p => memb p W) (adjEb HA') [u1])
        with (p := x) as [a [Ha Hch]]; auto.
      { intros a [<- | []]; unfold Gb; apply memb_true_iff; auto. }
      destruct Ha as [<- | []].
      eapply chain_impl; [| | exact Hch].
      - intros z Hz; apply memb_true_iff; exact Hz.
      - intros z y Hzy; apply adjEb_true_iff; exact Hzy. }
    assert (HKcomplete : forall x,
      chain (fun p => In p W) (adjE HA') u1 x -> In x K).
    { intros x Hch.
      eapply reach_from_complete with (a := u1); eauto.
      - constructor; [intros [] | constructor].
      - intros z [<- | []]; auto.
      - intros z Hz; apply memb_true_iff; auto.
      - left; auto.
      - eapply chain_impl; [| | exact Hch].
        + intros z Hz; unfold Gb; apply memb_true_iff; exact Hz.
        + intros z y Hzy; unfold Ab; apply adjEb_true_iff; exact Hzy. }
    assert (HendsA' : ends_in W HA').
    { intros f Hf; apply HendsA.
      apply in_remove_edge in Hf; tauto. }
    destruct (memb u2 K) eqn:Eu2.
    - (* the deleted edge closed a cycle *)
      left.
      apply memb_true_iff in Eu2.
      apply (spans_of_bridge W HA u1 u2 HA'); auto.
      apply incl_refl.
    - (* genuine split: find a crossing edge in HB *)
      right.
      assert (Hu2K : ~ In u2 K) by (apply memb_false_iff; auto).
      pose proof (HconnB u1 u2 Hu1 Hu2) as HchB.
      assert (Hu1K : memb u1 K = true)
        by (apply memb_true_iff; apply reach_seed_in).
      destruct (chain_crossing_bool (fun p => In p W) (adjE HB)
                  (fun x => memb x K) u1 u2 HchB Hu1K Eu2)
        as [u [v (Huv & Hpu & Hvq & HuKb & HvKb)]].
      apply memb_true_iff in HuKb.
      assert (HvnK : ~ In v K) by (apply memb_false_iff; auto).
      assert (HuW : In u W) by (exact (chain_good_r _ _ _ _ Hpu)).
      assert (HvW : In v W) by (exact (chain_good_l _ _ _ _ Hvq)).
      assert (Hstep' : ~ adjE HA' u v).
      { intros Hadj.
        apply HvnK, HKcomplete.
        eapply chain_snoc;
          [exact (HKsound u HuKb) | exact Hadj | exact HvW]. }
      assert (Hbridge : forall f,
          In f HB -> adjE (f :: HA') u v ->
          spans W (f :: HA')).
      { intros f HfB Hfadj.
        apply (spans_of_bridge W HA u1 u2 (f :: HA')); auto.
        - intros x Hx; right; auto.
        - intros x [<- | Hx]; [apply HendsB; auto | apply HendsA'; auto].
        - assert (Hu1u : chain (fun p => In p W) (adjE (f :: HA')) u1 u).
          { eapply chain_impl; [| | apply HKsound; exact HuKb]; auto.
            intros a b Hab; eapply adjE_incl; [| exact Hab].
            intros z Hz; right; auto. }
          assert (Hvu2 : chain (fun p => In p W) (adjE (f :: HA')) v u2).
          { assert (Hv2 : chain (fun p => In p W) (adjE HA') u1 v \/
                          chain (fun p => In p W) (adjE HA') u2 v)
              by (eapply endpoint_reach; eauto).
            destruct Hv2 as [Hv2 | Hv2].
            - exfalso; apply HvnK, HKcomplete; auto.
            - assert (Hv2' : chain (fun p => In p W) (adjE HA') v u2).
              { apply chain_sym; [| exact Hv2].
                intros a b; apply adjE_sym. }
              eapply chain_impl; [| | exact Hv2']; auto.
              intros a b Hab; eapply adjE_incl; [| exact Hab].
              intros z Hz; right; auto. }
          eapply chain_trans; [exact Hu1u|].
          eapply chain_step; [exact HuW | exact Hfadj | exact Hvu2]. }
      destruct Huv as [Hf | Hf].
      + exists (u, v).
        assert (Hne : (u, v) <> (u1, u2)).
        { intros Heq; inversion Heq; subst; contradiction. }
        assert (HfA : ~ In (u, v) HA).
        { intros HinA.
          apply Hstep'; left; apply in_remove_edge; auto. }
        refine (conj Hf (conj HfA (conj Hne _))).
        apply Hbridge; auto.
        left; left; auto.
      + exists (v, u).
        assert (Hne : (v, u) <> (u1, u2)).
        { intros Heq; inversion Heq; subst.
          exact (Hu2K HuKb). }
        assert (HfA : ~ In (v, u) HA).
        { intros HinA.
          apply Hstep'; right; apply in_remove_edge; auto. }
        refine (conj Hf (conj HfA (conj Hne _))).
        apply Hbridge; auto.
        right; left; auto.
  Qed.

  (** ** Cut moves cannot disconnect the surviving edges *)

  Lemma good_cut_keeps_union :
    forall st e W H1 H2,
      sg_wf st -> cturn st = true -> In e (avail st) ->
      sg_good st W H1 H2 ->
      connb (avail (sg_play st e) ++ claimed (sg_play st e)) = true.
  Proof.
    intros st e W H1 H2 Hwf Hc He
      (HW & HWV & HsW & HtW & HH1 & HH2 & Hshare & Hsp1 & Hsp2).
    assert (HeC : ~ In e (claimed st)).
    { intros Hcl; exact (Hwf e Hcl He). }
    apply connb_true_iff.
    destruct (ememb e H1) eqn:E1.
    - (* e is in H1, so H2 is intact *)
      apply ememb_true_iff in E1.
      assert (HeH2 : ~ In e H2)
        by (intros HinB; apply HeC, (Hshare e); auto).
      eapply (spans_connectedE W H2); eauto.
      intros x Hx.
      apply (in_union_cut st e x); auto.
      split; [apply HH2; auto|].
      intros ->; contradiction.
    - (* e is outside H1, so H1 is intact *)
      apply ememb_false_iff in E1.
      eapply (spans_connectedE W H1); eauto.
      intros x Hx.
      apply (in_union_cut st e x); auto.
      split; [apply HH1; auto|].
      intros ->; contradiction.
  Qed.

  (** Under the invariant Cut has not won. *)
  Lemma inv_outc_not_cut :
    forall st, sg_inv st -> sg_outc st <> Some (win true).
  Proof.
    intros st (W & H1 & H2 &
      (HW & HWV & HsW & HtW & HH1 & HH2 & Hshare & Hsp1 & Hsp2)) H.
    unfold sg_outc in H.
    destruct (connb (claimed st)); [discriminate|].
    assert (Hu : connb (avail st ++ claimed st) = true).
    { apply connb_true_iff.
      eapply (spans_connectedE W H1); eauto. }
    rewrite Hu in H; discriminate.
  Qed.

  Lemma outc_not_cut_of_connb :
    forall st,
      connb (avail st ++ claimed st) = true ->
      sg_outc st <> Some (win true).
  Proof.
    intros st Hu H; unfold sg_outc in H.
    destruct (connb (claimed st)); [discriminate|].
    rewrite Hu in H; discriminate.
  Qed.

    (** ** The Cut-move repair *)

  Lemma repair_core :
    forall st e W HA HB,
      sg_wf st -> cturn st = true -> In e (avail st) ->
      sg_good st W HA HB -> In e HA ->
      sg_outc (sg_play st e) = None ->
      exists c, In c (avail (sg_play st e)) /\
                sg_inv (sg_play (sg_play st e) c).
  Proof.
    intros st e W HA HB Hwf Hc He Hg HeA Hnone.
    pose proof Hg as
      (HW & HWV & HsW & HtW & HHA & HHB & Hshare & HspA & HspB).
    set (st' := sg_play st e) in *.
    assert (Hturn' : cturn st' = false) by (apply cturn_play_cut; auto).
    assert (HeC : ~ In e (claimed st))
      by (intros Hcl; exact (Hwf e Hcl He)).
    assert (HeB : ~ In e HB)
      by (intros HinB; apply HeC, (Hshare e); auto).
    assert (Hclaimed' : claimed st' = claimed st).
    { unfold st', sg_play; rewrite Hc; auto. }
    destruct e as [u1 u2].
    destruct (split_repair W HA HB u1 u2 HW HspA HspB HeA HeB)
      as [Hsp' | [f (HfB & HfA & Hfne & Hsp')]].
    - (* the deletion closed a cycle: the pruned certificate is good *)
      eapply (claim_any st' W (remove_edge (u1, u2) HA) HB); auto.
      apply sg_good_intro; auto.
      + intros x Hx.
        apply in_remove_edge in Hx; destruct Hx as [Hx Hne].
        apply union_cut_of; auto.
      + intros x Hx.
        apply union_cut_of; auto.
        intros ->; contradiction.
      + intros x Hx1 Hx2.
        rewrite Hclaimed'.
        apply in_remove_edge in Hx1; destruct Hx1 as [Hx1 _].
        exact (Hshare x Hx1 Hx2).
    - (* genuine split, repaired through the crossing edge [f] *)
      assert (HfU' : In f (avail st' ++ claimed st')).
      { apply union_cut_of; auto. }
      assert (Hshare' : forall x,
          In x (f :: remove_edge (u1, u2) HA) -> In x HB ->
          In x (f :: claimed st)).
      { intros x [<- | Hx] HxB; [left; auto|].
        apply in_remove_edge in Hx; destruct Hx as [Hx _].
        right; exact (Hshare x Hx HxB). }
      destruct (ememb f (claimed st)) eqn:Efc.
      + (* the crossing edge is already claimed: certificate holds now *)
        apply ememb_true_iff in Efc.
        eapply (claim_any st' W (f :: remove_edge (u1, u2) HA) HB); auto.
        apply sg_good_intro; auto.
        * intros x [<- | Hx].
          -- exact HfU'.
          -- apply in_remove_edge in Hx; destruct Hx as [Hx Hne].
             apply union_cut_of; auto.
        * intros x Hx.
          apply union_cut_of; auto.
          intros ->; contradiction.
        * intros x Hx1 Hx2.
          rewrite Hclaimed'.
          destruct (Hshare' x Hx1 Hx2) as [<- | Hcl]; auto.
      + (* the crossing edge is available: Short claims it *)
        apply ememb_false_iff in Efc.
        assert (HfAv : In f (avail st')).
        { apply in_app_or in HfU'; destruct HfU' as [Hf | Hf]; auto.
          rewrite Hclaimed' in Hf; contradiction. }
        exists f; split; auto.
        exists W, (f :: remove_edge (u1, u2) HA), HB.
        assert (Hcl'' : claimed (sg_play st' f) = f :: claimed st).
        { unfold sg_play; rewrite Hturn'; simpl; rewrite Hclaimed'; auto. }
        apply sg_good_intro; auto.
        * intros x [<- | Hx].
          -- apply union_short_of; auto.
          -- apply in_remove_edge in Hx; destruct Hx as [Hx Hne].
             apply union_short_of; auto.
             apply union_cut_of; auto.
        * intros x Hx.
          apply union_short_of; auto.
          apply union_cut_of; auto.
          intros ->; contradiction.
        * intros x Hx1 Hx2.
          rewrite Hcl''.
          exact (Hshare' x Hx1 Hx2).
  Qed.

  Lemma cut_then_claim :
    forall st e W H1 H2,
      sg_wf st -> cturn st = true -> In e (avail st) ->
      sg_good st W H1 H2 ->
      sg_outc (sg_play st e) = None ->
      exists c, In c (avail (sg_play st e)) /\
                sg_inv (sg_play (sg_play st e) c).
  Proof.
    intros st e W H1 H2 Hwf Hc He Hg Hnone.
    destruct (ememb e H1) eqn:E1.
    - apply ememb_true_iff in E1.
      apply (repair_core st e W H1 H2); auto.
    - destruct (ememb e H2) eqn:E2.
      + apply ememb_true_iff in E2.
        apply (repair_core st e W H2 H1); auto.
        apply sg_good_swap; auto.
      + (* the deleted edge touches neither certificate subgraph *)
        apply ememb_false_iff in E1; apply ememb_false_iff in E2.
        pose proof Hg as
          (HW & HWV & HsW & HtW & HH1 & HH2 & Hshare & Hsp1 & Hsp2).
        assert (Hclaimed' : claimed (sg_play st e) = claimed st).
        { unfold sg_play; rewrite Hc; auto. }
        eapply (claim_any (sg_play st e) W H1 H2); auto.
        * apply cturn_play_cut; auto.
        * apply sg_good_intro; auto.
          -- intros x Hx.
             apply union_cut_of; auto.
             intros ->; contradiction.
          -- intros x Hx.
             apply union_cut_of; auto.
             intros ->; contradiction.
          -- intros x Hx1 Hx2.
             rewrite Hclaimed'; exact (Hshare x Hx1 Hx2).
  Qed.

  (** ** Short's forcing theorem *)

  (** One unfolding step of the forcing predicate for Short. *)
  Lemma forces_short_S :
    forall f st,
      sg_outc st <> Some (win true) ->
      (sg_outc st = None -> cturn st = true ->
        forall e, In e (avail st) ->
        forces sg_moves sg_play sg_amove sg_outc false f (sg_play st e)) ->
      (sg_outc st = None -> cturn st = false ->
        exists e, In e (avail st) /\
        forces sg_moves sg_play sg_amove sg_outc false f (sg_play st e)) ->
      forces sg_moves sg_play sg_amove sg_outc false (S f) st.
  Proof.
    intros f st Hnc Hcut Hshort.
    apply (proj2 (forces_S_iff sg_moves sg_play sg_amove sg_outc false f st)).
    destruct (sg_outc st) as [o|] eqn:Eo.
    - destruct o as [w|]; [destruct w; simpl; congruence|].
      exfalso; exact (sg_outc_not_drawn st Eo).
    - unfold sg_amove.
      destruct (cturn st) eqn:Ec; simpl.
      + intros e He; apply Hcut; auto.
      + apply Hshort; auto.
  Qed.

  Lemma avail_play_lt :
    forall st e,
      In e (avail st) ->
      length (avail (sg_play st e)) < length (avail st).
  Proof.
    intros st e He; unfold sg_play.
    destruct (cturn st); simpl; apply remove_edge_length_lt; auto.
  Qed.

    (** Short's strategy: force the win within two plies per available edge. *)
  Lemma short_forces_aux :
    forall k st,
      length (avail st) < k ->
      sg_wf st -> sg_inv st -> cturn st = true ->
      forces sg_moves sg_play sg_amove sg_outc false
        (2 * length (avail st)) st.
  Proof.
    induction k as [|k IH]; intros st Hk Hwf Hinv Hc; [lia|].
    destruct (avail st) as [|e0 rest] eqn:Ea.
    - (* no available edges: the certificate lies in the claimed edges *)
      destruct Hinv as (W & H1 & H2 &
        (HW & HWV & HsW & HtW & HH1 & HH2 & Hshare & Hsp1 & Hsp2)).
      assert (Hconn : connb (claimed st) = true).
      { apply connb_true_iff.
        eapply (spans_connectedE W H1); eauto.
        intros x Hx.
        specialize (HH1 x Hx); rewrite Ea in HH1; exact HH1. }
      assert (Hout : sg_outc st = Some (win false))
        by (unfold sg_outc; rewrite Hconn; reflexivity).
      apply (proj2 (forces_0_iff sg_moves sg_play sg_amove sg_outc false st)).
      rewrite Hout; reflexivity.
    - rewrite <- Ea.
      rewrite <- Ea in Hk.
      assert (Hm : 1 <= length (avail st)) by (rewrite Ea; simpl; lia).
      replace (2 * length (avail st))
        with (S (S (2 * length (avail st) - 2))) by lia.
      apply forces_short_S.
      + apply inv_outc_not_cut; auto.
      + intros Hnone _ e He.
        destruct Hinv as (W & H1 & H2 & Hg).
        apply forces_short_S.
        * apply outc_not_cut_of_connb.
          eapply good_cut_keeps_union; eauto.
        * intros _ Hc'.
          rewrite (cturn_play_cut st e Hc) in Hc'; discriminate.
        * intros Hnone' _.
          destruct (cut_then_claim st e W H1 H2 Hwf Hc He Hg Hnone')
            as [c [HcAv Hinv'']].
          exists c; split; [exact HcAv|].
          assert (Hone : 1 <= length (avail (sg_play st e))).
          { destruct (avail (sg_play st e)); [destruct HcAv | simpl; lia]. }
          assert (Hlt' : length (avail (sg_play st e)) < length (avail st))
            by (apply avail_play_lt; auto).
          assert (Hlt'' : length (avail (sg_play (sg_play st e) c))
                          < length (avail (sg_play st e)))
            by (apply avail_play_lt; auto).
          apply (forces_le sg_moves sg_play sg_amove sg_outc false
                   (2 * length (avail (sg_play (sg_play st e) c))));
            [lia|].
          apply IH.
          -- lia.
          -- apply sg_wf_play, sg_wf_play; auto.
          -- exact Hinv''.
          -- apply cturn_play_short, cturn_play_cut; auto.
      + intros _ Hc'; congruence.
  Qed.

    (** Lehman's theorem, positive direction: Short wins moving second. *)
  Theorem lehman_short_wins :
    forall A W H1 H2,
      NoDup W -> incl W V -> In strm W -> In trm W ->
      incl H1 A -> incl H2 A ->
      (forall e, In e H1 -> In e H2 -> False) ->
      spans W H1 -> spans W H2 ->
      forces sg_moves sg_play sg_amove sg_outc false
        (2 * length A) (MkSG A [] true).
  Proof.
    intros A W H1 H2 HW HWV HsW HtW HH1 HH2 Hdisj Hsp1 Hsp2.
    apply (short_forces_aux (S (length A)) (MkSG A [] true)).
    - simpl; lia.
    - intros e He; simpl in He; destruct He.
    - exists W, H1, H2.
      apply sg_good_intro; auto.
      + intros x Hx; apply in_or_app; left; apply HH1; auto.
      + intros x Hx; apply in_or_app; left; apply HH2; auto.
    - reflexivity.
  Qed.

  (** Adding edges cannot break a connection. *)
  Lemma connectedE_mono :
    forall E F, incl E F -> connectedE E -> connectedE F.
  Proof.
    intros E F Hsub Hch.
    eapply chain_impl; [| | exact Hch]; auto.
    intros x y [Hxy | Hxy]; [left | right]; apply Hsub; exact Hxy.
  Qed.

  Lemma connb_mono :
    forall E F, incl E F -> connb E = true -> connb F = true.
  Proof.
    intros E F Hsub HE.
    apply connb_true_iff, (connectedE_mono E); auto.
    apply connb_true_iff; exact HE.
  Qed.

  (** Cut has already won when even every edge together fails to connect. *)
  Theorem cut_wins_of_disconnected :
    forall A c t,
      connb (A ++ c) = false ->
      forces sg_moves sg_play sg_amove sg_outc true 0 (MkSG A c t).
  Proof.
    intros A c t H.
    apply (proj2 (forces_0_iff sg_moves sg_play sg_amove sg_outc true
                    (MkSG A c t))).
    unfold sg_outc; simpl.
    assert (Hc : connb c = false).
    { destruct (connb c) eqn:E; auto.
      exfalso.
      assert (Hu : connb (A ++ c) = true).
      { apply (connb_mono c); auto.
        intros x Hx; apply in_or_app; right; exact Hx. }
      congruence. }
    rewrite Hc, H; reflexivity.
  Qed.

  (** So Short cannot force a win unless the edges can join the terminals. *)
  Corollary short_needs_connected :
    forall A c t fuel,
      connb (A ++ c) = false ->
      forces sg_moves sg_play sg_amove sg_outc false fuel (MkSG A c t) ->
      False.
  Proof.
    intros A c t fuel H Hs.
    apply (forces_not_both sg_moves sg_play sg_amove sg_outc fuel
             (MkSG A c t)); [| exact Hs].
    apply (forces_le sg_moves sg_play sg_amove sg_outc true 0 fuel);
      [lia | apply cut_wins_of_disconnected; exact H].
  Qed.

  (** Lehman's theorem, moving first: claim the shared edge, then reply. *)
  Theorem lehman_short_first :
    forall A e0 W H1 H2,
      In e0 A ->
      NoDup W -> incl W V -> In strm W -> In trm W ->
      incl H1 A -> incl H2 A ->
      (forall e, In e H1 -> In e H2 -> e = e0) ->
      spans W H1 -> spans W H2 ->
      forces sg_moves sg_play sg_amove sg_outc false
        (S (2 * length (remove_edge e0 A))) (MkSG A [] false).
  Proof.
    intros A e0 W H1 H2 He0 HW HWV HsW HtW HH1 HH2 Hsh Hsp1 Hsp2.
    assert (Hu : connb (A ++ []) = true).
    { rewrite app_nil_r.
      apply connb_true_iff, (spans_connectedE W H1); auto. }
    apply (proj2 (forces_S_iff sg_moves sg_play sg_amove sg_outc false
                    (2 * length (remove_edge e0 A)) (MkSG A [] false))).
    unfold sg_outc; simpl.
    destruct (connb []) eqn:Ec.
    - auto.
    - rewrite Hu; simpl.
      exists e0; split; [exact He0|].
      change (forces sg_moves sg_play sg_amove sg_outc false
                (2 * length (remove_edge e0 A))
                (MkSG (remove_edge e0 A) [e0] true)).
      apply (short_forces_aux (S (length (remove_edge e0 A)))
               (MkSG (remove_edge e0 A) [e0] true)).
      + simpl; lia.
      + intros e He Ha; simpl in He, Ha.
        destruct He as [<- | []].
        apply in_remove_edge in Ha.
        destruct Ha as [_ Hne]; apply Hne; auto.
      + exists W, H1, H2.
        apply sg_good_intro; auto.
        * intros x Hx; simpl.
          destruct (edge_eq_dec x e0) as [-> | Hne].
          -- apply in_or_app; right; left; auto.
          -- apply in_or_app; left; apply in_remove_edge; split; auto.
        * intros x Hx; simpl.
          destruct (edge_eq_dec x e0) as [-> | Hne].
          -- apply in_or_app; right; left; auto.
          -- apply in_or_app; left; apply in_remove_edge; split; auto.
        * intros e He1 He2; simpl.
          left; symmetry; apply (Hsh e); auto.
      + reflexivity.
  Qed.

End Shannon.

(** * Boolean certificates *)

(** Sound checkers discharging the spanning-pair hypotheses by computation. *)

Definition inclEb (E F : list edge) : bool := forallb (fun e => ememb e F) E.

Lemma inclEb_incl : forall E F, inclEb E F = true -> incl E F.
Proof.
  intros E F H x Hx.
  unfold inclEb in H; rewrite forallb_forall in H.
  apply ememb_true_iff; auto.
Qed.

Definition edisjb (E F : list edge) : bool :=
  forallb (fun e => negb (ememb e F)) E.

Lemma edisjb_disjoint :
  forall E F, edisjb E F = true ->
  forall e, In e E -> In e F -> False.
Proof.
  intros E F H e He Hf.
  unfold edisjb in H; rewrite forallb_forall in H.
  specialize (H e He).
  rewrite negb_true_iff in H.
  apply ememb_false_iff in H; contradiction.
Qed.

Definition inclCb (W U : list cell) : bool := forallb (fun p => memb p U) W.

Lemma inclCb_incl : forall W U, inclCb W U = true -> incl W U.
Proof.
  intros W U H x Hx.
  unfold inclCb in H; rewrite forallb_forall in H.
  apply memb_true_iff; auto.
Qed.

Fixpoint cnodupb (l : list cell) : bool :=
  match l with
  | [] => true
  | x :: rest => negb (memb x rest) && cnodupb rest
  end.

Lemma cnodupb_NoDup : forall l, cnodupb l = true -> NoDup l.
Proof.
  induction l as [|x l IH]; intros H; simpl in H; [constructor|].
  apply andb_true_iff in H; destruct H as [H1 H2].
  constructor; [| apply IH; auto].
  apply negb_true_iff in H1.
  apply memb_false_iff; auto.
Qed.

Definition ends_inb (W : list cell) (H : list edge) : bool :=
  forallb (fun e => memb (fst e) W && memb (snd e) W) H.

Definition connallb (W : list cell) (H : list edge) : bool :=
  forallb (fun u =>
    forallb (fun v =>
      memb v (reach_from W (fun p => memb p W) (adjEb H) [u])) W) W.

Definition spansb (W : list cell) (H : list edge) : bool :=
  ends_inb W H && connallb W H.

Lemma spansb_spans : forall W H, spansb W H = true -> spans W H.
Proof.
  intros W H Hb.
  unfold spansb in Hb; apply andb_true_iff in Hb; destruct Hb as [He Hc].
  split.
  - intros e Hin.
    unfold ends_inb in He; rewrite forallb_forall in He.
    specialize (He e Hin); apply andb_true_iff in He.
    destruct He as [H1 H2]; split; apply memb_true_iff; auto.
  - intros u v Hu Hv.
    unfold connallb in Hc; rewrite forallb_forall in Hc.
    specialize (Hc u Hu); rewrite forallb_forall in Hc.
    specialize (Hc v Hv); apply memb_true_iff in Hc.
    destruct (reach_from_sound W (fun p => memb p W) (adjEb H) [u])
      with (p := v) as [a [Ha Hch]]; auto.
    { intros a [<- | []]; unfold Gb; apply memb_true_iff; auto. }
    destruct Ha as [<- | []].
    eapply chain_impl; [| | exact Hch].
    + intros z Hz; apply memb_true_iff; exact Hz.
    + intros z y Hzy; apply adjEb_true_iff; exact Hzy.
Qed.

(** * A solved instance *)

(** K4 with opposite terminals carries two edge-disjoint spanning trees. *)

Definition vK4 : list cell := [(0, 0); (1, 0); (2, 0); (3, 0)].
Definition sK4 : cell := (0, 0).
Definition tK4 : cell := (3, 0).

Definition h1K4 : list edge :=
  [((0, 0), (1, 0)); ((1, 0), (3, 0)); ((3, 0), (2, 0))].
Definition h2K4 : list edge :=
  [((0, 0), (2, 0)); ((2, 0), (1, 0)); ((0, 0), (3, 0))].
Definition aK4 : list edge := h1K4 ++ h2K4.

Theorem k4_short_wins :
  forces sg_moves sg_play sg_amove (sg_outc vK4 sK4 tK4) false
    (2 * length aK4) (MkSG aK4 [] true).
Proof.
  exact (lehman_short_wins vK4
    (cnodupb_NoDup vK4 eq_refl)
    sK4 tK4
    (proj1 (memb_true_iff sK4 vK4) eq_refl)
    aK4 vK4 h1K4 h2K4
    (cnodupb_NoDup vK4 eq_refl)
    (inclCb_incl vK4 vK4 eq_refl)
    (proj1 (memb_true_iff sK4 vK4) eq_refl)
    (proj1 (memb_true_iff tK4 vK4) eq_refl)
    (inclEb_incl h1K4 aK4 eq_refl)
    (inclEb_incl h2K4 aK4 eq_refl)
    (edisjb_disjoint h1K4 h2K4 eq_refl)
    (spansb_spans vK4 h1K4 eq_refl)
    (spansb_spans vK4 h2K4 eq_refl)).
Qed.

(** The generic forcing checker confirms the same instance by search. *)
Example k4_short_wins_checked :
  forces_b sg_moves sg_play sg_amove (sg_outc vK4 sK4 tK4) false
    (2 * length aK4) (MkSG aK4 [] true) = true.
Proof. vm_compute; reflexivity. Qed.
